debug: false
secret: 8A4N3MFhnxXb4SnrJhnRzDPYULRm66nt
invitation: true
#moreuRoot: / # 前端目录，如果定义则优先使用该目录下的前端文件，否则使用内置的前端页面

email:
  host: smtpdm.aliyun.com:25
  sender: no-reply@saltbo.fun
  username: Moreu
  password: mG077URe2Wh9

database:
  driver: mysql
  dsn: root:admin@(localhost:3306)/zpan?charset=utf8&parseTime=True&loc=Local